/**
 * characterCatalogService.ts
 *
 * Local character portrait catalog — replaces live ComfyUI generation as primary
 * portrait source. Reads the static catalog.json generated by
 * scripts/generate-character-catalog.js.
 *
 * Usage:
 *   getCatalogPortraits(charClass, race?)   → array of CatalogEntry
 *   getCatalogPortrait(charClass, race?)    → best single CatalogEntry or null
 *   getCatalogPortraitUri(charClass, race?) → resolved require() path or null
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export type CatalogEntry = {
  key:         string;
  charClass:   string;
  race:        string;
  subclass:    string | null;
  portraitPath: string;
  /** Relative paths to expression images, keyed by expression name.
   *  Populated by generate-expressions.js after portrait generation. */
  expressions: Record<string, string> | null;
};

// ---------------------------------------------------------------------------
// Static catalog map — populated at build time from catalog.json.
// We use a lazy-loaded approach: import catalog.json statically so Metro
// bundles it; fall back to an empty map if the file does not yet exist.
// ---------------------------------------------------------------------------

let _catalog: Record<string, CatalogEntry> | null = null;

function getCatalog(): Record<string, CatalogEntry> {
  if (_catalog !== null) return _catalog;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const raw = require('../../assets/images/characters/catalog.json') as Record<string, CatalogEntry>;
    _catalog = raw;
  } catch {
    // catalog.json not yet generated — fall back to empty map
    _catalog = {};
  }
  return _catalog;
}

// ---------------------------------------------------------------------------
// Require-map — Metro resolves static image paths at build time.
// To support dynamic lookup we use a manual require map for all portraits.
// This map is generated from the same CATALOG_ENTRIES list as the script.
// ---------------------------------------------------------------------------

/**
 * Returns a require() path suitable for <Image source={...} /> given a
 * relative asset path like "assets/images/characters/fighter/fighter_elf_2/portrait.png".
 *
 * Metro cannot resolve truly dynamic require() at runtime, so we maintain
 * a static map here. New entries must be added as they are generated.
 *
 * For catalog entries that have not yet been generated (file absent), returns null.
 */
export function requireCatalogPortrait(entry: CatalogEntry): number | null {
  return PORTRAIT_REQUIRE_MAP[entry.key] ?? null;
}

/**
 * Returns the require() map for a specific expression of a catalog entry.
 * e.g. requireCatalogExpression(entry, 'angry') → require(...expression_angry.png)
 */
export function requireCatalogExpression(
  entry: CatalogEntry,
  expression: string,
): number | null {
  const map = EXPRESSION_REQUIRE_MAP[entry.key];
  return map?.[expression] ?? null;
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Returns all catalog entries matching the given class (and optionally race).
 * If no entries exist, returns [].
 */
export function getCatalogPortraits(
  charClass: string,
  race?: string,
): CatalogEntry[] {
  const catalog = getCatalog();
  return Object.values(catalog).filter(e => {
    if (e.charClass !== charClass) return false;
    if (race && e.race !== race) return false;
    return true;
  });
}

/**
 * Returns the best single catalog entry for the given class/race.
 * Priority: exact class+race match → class-only match → null.
 */
export function getCatalogPortrait(
  charClass: string,
  race?: string,
): CatalogEntry | null {
  const exact = race
    ? getCatalogPortraits(charClass, race)
    : [];
  if (exact.length > 0) return exact[0];

  const fallback = getCatalogPortraits(charClass);
  return fallback.length > 0 ? fallback[0] : null;
}

/**
 * Returns true if the catalog has at least one portrait for the given class.
 */
export function hasCatalogPortraits(charClass: string): boolean {
  const catalog = getCatalog();
  return Object.values(catalog).some(e => e.charClass === charClass);
}

/**
 * Returns all expression keys available for a given catalog entry.
 * e.g. ['neutral', 'angry', 'happy', ...]
 */
export function getCatalogExpressionKeys(entry: CatalogEntry): string[] {
  if (!entry.expressions) return [];
  return Object.keys(entry.expressions);
}

// ---------------------------------------------------------------------------
// Static require maps — must be updated as images are generated.
//
// The keys match CatalogEntry.key exactly.
// When an image doesn't exist yet, the entry is simply absent from the map.
//
// metro.config.js resolves these at bundle time, so we use require() literals.
// ---------------------------------------------------------------------------

const PORTRAIT_REQUIRE_MAP: Record<string, number> = {
  // ── BARBARIAN ──────────────────────────────────────────────────────────────
  'barbarian_human_1':      require('../../assets/images/characters/barbarian/barbarian_human_1/portrait.png'),
  'barbarian_half-orc_2':   require('../../assets/images/characters/barbarian/barbarian_half-orc_2/portrait.png'),
  'barbarian_dwarf_3':      require('../../assets/images/characters/barbarian/barbarian_dwarf_3/portrait.png'),
  'barbarian_elf_4':        require('../../assets/images/characters/barbarian/barbarian_elf_4/portrait.png'),
  // ── BARD ───────────────────────────────────────────────────────────────────
  'bard_half-elf_1':        require('../../assets/images/characters/bard/bard_half-elf_1/portrait.png'),
  'bard_human_2':           require('../../assets/images/characters/bard/bard_human_2/portrait.png'),
  'bard_tiefling_3':        require('../../assets/images/characters/bard/bard_tiefling_3/portrait.png'),
  'bard_gnome_4':           require('../../assets/images/characters/bard/bard_gnome_4/portrait.png'),
  // ── CLERIC ─────────────────────────────────────────────────────────────────
  'cleric_human_1':         require('../../assets/images/characters/cleric/cleric_human_1/portrait.png'),
  'cleric_dwarf_2':         require('../../assets/images/characters/cleric/cleric_dwarf_2/portrait.png'),
  'cleric_elf_3':           require('../../assets/images/characters/cleric/cleric_elf_3/portrait.png'),
  'cleric_half-elf_4':      require('../../assets/images/characters/cleric/cleric_half-elf_4/portrait.png'),
  'cleric_dragonborn_5':    require('../../assets/images/characters/cleric/cleric_dragonborn_5/portrait.png'),
  // ── DRUID ──────────────────────────────────────────────────────────────────
  'druid_elf_1':            require('../../assets/images/characters/druid/druid_elf_1/portrait.png'),
  'druid_human_2':          require('../../assets/images/characters/druid/druid_human_2/portrait.png'),
  'druid_gnome_3':          require('../../assets/images/characters/druid/druid_gnome_3/portrait.png'),
  'druid_half-elf_4':       require('../../assets/images/characters/druid/druid_half-elf_4/portrait.png'),
  // ── FIGHTER ────────────────────────────────────────────────────────────────
  'fighter_human_1':        require('../../assets/images/characters/fighter/fighter_human_1/portrait.png'),
  'fighter_elf_2':          require('../../assets/images/characters/fighter/fighter_elf_2/portrait.png'),
  'fighter_dwarf_3':        require('../../assets/images/characters/fighter/fighter_dwarf_3/portrait.png'),
  'fighter_half-orc_4':     require('../../assets/images/characters/fighter/fighter_half-orc_4/portrait.png'),
  // ── MONK ───────────────────────────────────────────────────────────────────
  'monk_human_1':           require('../../assets/images/characters/monk/monk_human_1/portrait.png'),
  'monk_elf_2':             require('../../assets/images/characters/monk/monk_elf_2/portrait.png'),
  'monk_halfling_3':        require('../../assets/images/characters/monk/monk_halfling_3/portrait.png'),
  'monk_half-elf_4':        require('../../assets/images/characters/monk/monk_half-elf_4/portrait.png'),
  // ── PALADIN ────────────────────────────────────────────────────────────────
  'paladin_human_1':        require('../../assets/images/characters/paladin/paladin_human_1/portrait.png'),
  'paladin_dwarf_2':        require('../../assets/images/characters/paladin/paladin_dwarf_2/portrait.png'),
  'paladin_half-elf_3':     require('../../assets/images/characters/paladin/paladin_half-elf_3/portrait.png'),
  'paladin_tiefling_4':     require('../../assets/images/characters/paladin/paladin_tiefling_4/portrait.png'),
  'paladin_dragonborn_5':   require('../../assets/images/characters/paladin/paladin_dragonborn_5/portrait.png'),
  // ── RANGER ─────────────────────────────────────────────────────────────────
  'ranger_elf_1':           require('../../assets/images/characters/ranger/ranger_elf_1/portrait.png'),
  'ranger_human_2':         require('../../assets/images/characters/ranger/ranger_human_2/portrait.png'),
  'ranger_halfling_3':      require('../../assets/images/characters/ranger/ranger_halfling_3/portrait.png'),
  'ranger_half-elf_4':      require('../../assets/images/characters/ranger/ranger_half-elf_4/portrait.png'),
  // ── ROGUE ──────────────────────────────────────────────────────────────────
  'rogue_halfling_1':       require('../../assets/images/characters/rogue/rogue_halfling_1/portrait.png'),
  'rogue_human_2':          require('../../assets/images/characters/rogue/rogue_human_2/portrait.png'),
  'rogue_tiefling_3':       require('../../assets/images/characters/rogue/rogue_tiefling_3/portrait.png'),
  'rogue_half-elf_4':       require('../../assets/images/characters/rogue/rogue_half-elf_4/portrait.png'),
  // ── SORCERER ───────────────────────────────────────────────────────────────
  'sorcerer_human_1':       require('../../assets/images/characters/sorcerer/sorcerer_human_1/portrait.png'),
  'sorcerer_tiefling_2':    require('../../assets/images/characters/sorcerer/sorcerer_tiefling_2/portrait.png'),
  'sorcerer_elf_3':         require('../../assets/images/characters/sorcerer/sorcerer_elf_3/portrait.png'),
  'sorcerer_half-elf_4':    require('../../assets/images/characters/sorcerer/sorcerer_half-elf_4/portrait.png'),
  // ── WARLOCK ────────────────────────────────────────────────────────────────
  'warlock_tiefling_1':     require('../../assets/images/characters/warlock/warlock_tiefling_1/portrait.png'),
  'warlock_human_2':        require('../../assets/images/characters/warlock/warlock_human_2/portrait.png'),
  'warlock_elf_3':          require('../../assets/images/characters/warlock/warlock_elf_3/portrait.png'),
  'warlock_half-orc_4':     require('../../assets/images/characters/warlock/warlock_half-orc_4/portrait.png'),
  // ── WIZARD — generate with: node scripts/generate-character-catalog.js --class wizard ──
  // wizard_human_1:       require('../../assets/images/characters/wizard/wizard_human_1/portrait.png'),
  // wizard_gnome_2:       require('../../assets/images/characters/wizard/wizard_gnome_2/portrait.png'),
  // wizard_elf_3:         require('../../assets/images/characters/wizard/wizard_elf_3/portrait.png'),
  // wizard_half-elf_4:    require('../../assets/images/characters/wizard/wizard_half-elf_4/portrait.png'),
  // wizard_tiefling_5:    require('../../assets/images/characters/wizard/wizard_tiefling_5/portrait.png'),
};

const EXPRESSION_REQUIRE_MAP: Record<string, Record<string, number>> = {
  // populated after running generate-expressions.js for each portrait
};

// ---------------------------------------------------------------------------
// Utility: pick a catalog portrait for an NPC party member deterministically.
// Used by GuildScreen and worldSimulator when assigning portraits to AI parties.
// ---------------------------------------------------------------------------

/**
 * Returns a catalog entry deterministically based on a seed string.
 * Used for AI/NPC party members so they always get the same portrait.
 */
export function getCatalogPortraitForNPC(
  charClass: string,
  race: string,
  seedString: string,
): CatalogEntry | null {
  const candidates = getCatalogPortraits(charClass, race);
  if (candidates.length === 0) {
    // fallback: any entry for this class
    const classFallback = getCatalogPortraits(charClass);
    if (classFallback.length === 0) return null;
    const idx = Math.abs(hashString(seedString)) % classFallback.length;
    return classFallback[idx];
  }
  const idx = Math.abs(hashString(seedString)) % candidates.length;
  return candidates[idx];
}

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = Math.imul(31, h) + s.charCodeAt(i) | 0;
  }
  return h;
}
