/**
 * characterCatalogService.ts
 *
 * Local character portrait catalog — replaces live ComfyUI generation as primary
 * portrait source. Reads the static catalog.json generated by
 * scripts/generate-character-catalog.js.
 *
 * Usage:
 *   getCatalogPortraits(charClass, race?)   → array of CatalogEntry
 *   getCatalogPortrait(charClass, race?)    → best single CatalogEntry or null
 *   getCatalogPortraitUri(charClass, race?) → resolved require() path or null
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export type CatalogEntry = {
  key:         string;
  charClass:   string;
  race:        string;
  subclass:    string | null;
  portraitPath: string;
  /** Relative paths to expression images, keyed by expression name.
   *  Populated by generate-expressions.js after portrait generation. */
  expressions: Record<string, string> | null;
};

// ---------------------------------------------------------------------------
// Static catalog map — populated at build time from catalog.json.
// We use a lazy-loaded approach: import catalog.json statically so Metro
// bundles it; fall back to an empty map if the file does not yet exist.
// ---------------------------------------------------------------------------

let _catalog: Record<string, CatalogEntry> | null = null;

function getCatalog(): Record<string, CatalogEntry> {
  if (_catalog !== null) return _catalog;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const raw = require('../../assets/images/characters/catalog.json') as Record<string, CatalogEntry>;
    _catalog = raw;
  } catch {
    // catalog.json not yet generated — fall back to empty map
    _catalog = {};
  }
  return _catalog;
}

// ---------------------------------------------------------------------------
// Require-map — Metro resolves static image paths at build time.
// To support dynamic lookup we use a manual require map for all portraits.
// This map is generated from the same CATALOG_ENTRIES list as the script.
// ---------------------------------------------------------------------------

/**
 * Returns a require() path suitable for <Image source={...} /> given a
 * relative asset path like "assets/images/characters/fighter/fighter_elf_2/portrait.png".
 *
 * Metro cannot resolve truly dynamic require() at runtime, so we maintain
 * a static map here. New entries must be added as they are generated.
 *
 * For catalog entries that have not yet been generated (file absent), returns null.
 */
export function requireCatalogPortrait(entry: CatalogEntry): number | null {
  return PORTRAIT_REQUIRE_MAP[entry.key] ?? null;
}

/**
 * Returns the require() map for a specific expression of a catalog entry.
 * e.g. requireCatalogExpression(entry, 'angry') → require(...expression_angry.png)
 */
export function requireCatalogExpression(
  entry: CatalogEntry,
  expression: string,
): number | null {
  const map = EXPRESSION_REQUIRE_MAP[entry.key];
  return map?.[expression] ?? null;
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/**
 * Returns all catalog entries matching the given class (and optionally race).
 * If no entries exist, returns [].
 */
export function getCatalogPortraits(
  charClass: string,
  race?: string,
): CatalogEntry[] {
  const catalog = getCatalog();
  return Object.values(catalog).filter(e => {
    if (e.charClass !== charClass) return false;
    if (race && e.race !== race) return false;
    return true;
  });
}

/**
 * Returns the best single catalog entry for the given class/race.
 * Priority: exact class+race match → class-only match → null.
 */
export function getCatalogPortrait(
  charClass: string,
  race?: string,
): CatalogEntry | null {
  const exact = race
    ? getCatalogPortraits(charClass, race)
    : [];
  if (exact.length > 0) return exact[0];

  const fallback = getCatalogPortraits(charClass);
  return fallback.length > 0 ? fallback[0] : null;
}

/**
 * Returns true if the catalog has at least one portrait for the given class.
 */
export function hasCatalogPortraits(charClass: string): boolean {
  const catalog = getCatalog();
  return Object.values(catalog).some(e => e.charClass === charClass);
}

/**
 * Returns all expression keys available for a given catalog entry.
 * e.g. ['neutral', 'angry', 'happy', ...]
 */
export function getCatalogExpressionKeys(entry: CatalogEntry): string[] {
  if (!entry.expressions) return [];
  return Object.keys(entry.expressions);
}

// ---------------------------------------------------------------------------
// Static require maps — must be updated as images are generated.
//
// The keys match CatalogEntry.key exactly.
// When an image doesn't exist yet, the entry is simply absent from the map.
//
// metro.config.js resolves these at bundle time, so we use require() literals.
// ---------------------------------------------------------------------------

const PORTRAIT_REQUIRE_MAP: Record<string, number> = {
  // populated automatically when portraits are present in the bundle
  // ── BARBARIAN ──────────────────────────────────────────────────────────────
  // barbarian_human_1:    require('../../assets/images/characters/barbarian/barbarian_human_1/portrait.png'),
  // barbarian_half-orc_2: require('../../assets/images/characters/barbarian/barbarian_half-orc_2/portrait.png'),
  // ... (uncomment after running generate-character-catalog.js)
};

const EXPRESSION_REQUIRE_MAP: Record<string, Record<string, number>> = {
  // populated after running generate-expressions.js for each portrait
};

// ---------------------------------------------------------------------------
// Utility: pick a catalog portrait for an NPC party member deterministically.
// Used by GuildScreen and worldSimulator when assigning portraits to AI parties.
// ---------------------------------------------------------------------------

/**
 * Returns a catalog entry deterministically based on a seed string.
 * Used for AI/NPC party members so they always get the same portrait.
 */
export function getCatalogPortraitForNPC(
  charClass: string,
  race: string,
  seedString: string,
): CatalogEntry | null {
  const candidates = getCatalogPortraits(charClass, race);
  if (candidates.length === 0) {
    // fallback: any entry for this class
    const classFallback = getCatalogPortraits(charClass);
    if (classFallback.length === 0) return null;
    const idx = Math.abs(hashString(seedString)) % classFallback.length;
    return classFallback[idx];
  }
  const idx = Math.abs(hashString(seedString)) % candidates.length;
  return candidates[idx];
}

function hashString(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) {
    h = Math.imul(31, h) + s.charCodeAt(i) | 0;
  }
  return h;
}
