/**
 * src/services/spriteDbService.ts
 *
 * Reads assets/sprites/enemies/index.json (generated by scripts/generate-sprites.js)
 * and exposes typed accessors to the app.
 *
 * The index.json is bundled as a static asset via Metro.
 * Require it once and cache it — no SQLite or network needed at runtime.
 */

import type { EnemyType, AnimationType, SpriteSet } from './enemySpriteService';

// Metro will bundle this JSON along with the app
// eslint-disable-next-line @typescript-eslint/no-require-imports
const INDEX: SpriteIndex = require('../../assets/sprites/enemies/index.json');

// ─── Types ───────────────────────────────────────────────────────────────────
interface SpriteIndex {
  [enemyKey: string]: {
    base: string;
    animations: {
      [anim: string]: string[]; // 4 frame paths
    };
  };
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Returns true if pre-generated sprites exist for this enemy.
 */
export function hasPrebuiltSprites(enemy: EnemyType): boolean {
  return enemy in INDEX;
}

/**
 * Returns the `require()`-ready asset path for the base sprite.
 * These are relative paths — convert to Image source uri as needed.
 */
export function getBaseSpritePath(enemy: EnemyType): string | null {
  return INDEX[enemy]?.base ?? null;
}

/**
 * Returns 4 frame paths for a given animation.
 */
export function getAnimationFramePaths(
  enemy: EnemyType,
  anim: AnimationType,
): string[] | null {
  const frames = INDEX[enemy]?.animations?.[anim];
  if (!frames || frames.length < 4) return null;
  return frames;
}

/**
 * Builds a SpriteSet of asset paths (not base64 URIs) for use with
 * React Native's Image component: source={{ uri: `asset://${path}` }}
 * or via react-native-asset bundling.
 *
 * Returns null if any animation set is missing.
 */
export function getPrebuiltSpriteSet(enemy: EnemyType): PrebuiltSpriteSet | null {
  const entry = INDEX[enemy];
  if (!entry) return null;

  const anims: Record<string, string[]> = {};
  for (const anim of ['idle', 'run', 'attack', 'damage', 'death'] as AnimationType[]) {
    const frames = entry.animations[anim];
    if (!frames || frames.length < 4) return null;
    anims[anim] = frames;
  }

  return {
    base:       entry.base,
    animations: anims as { [K in AnimationType]: string[] },
  };
}

/**
 * Returns all enemy keys that have pre-built sprites in the index.
 */
export function listPrebuiltEnemies(): EnemyType[] {
  return Object.keys(INDEX) as EnemyType[];
}

// ─── Types ───────────────────────────────────────────────────────────────────
export interface PrebuiltSpriteSet {
  base: string;
  animations: { [K in AnimationType]: string[] }; // 4 frames each
}
