// Static require map for monster illustrations.
// React Native's Metro bundler requires static string paths — no dynamic requires.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const MONSTER_ILLUSTRATIONS: Record<string, any> = {
  banshee:         require('../../assets/images/monsters/banshee/illustration.webp'),
  berserker:       require('../../assets/images/monsters/berserker/illustration.webp'),
  cultist:         require('../../assets/images/monsters/cultist/illustration.webp'),
  dark_knight:     require('../../assets/images/monsters/dark_knight/illustration.webp'),
  demon:           require('../../assets/images/monsters/demon/illustration.webp'),
  dire_rat:        require('../../assets/images/monsters/dire_rat/illustration.webp'),
  dire_wolf:       require('../../assets/images/monsters/dire_wolf/illustration.webp'),
  dragon_wyrmling: require('../../assets/images/monsters/dragon_wyrmling/illustration.webp'),
  ghoul:           require('../../assets/images/monsters/ghoul/illustration.webp'),
  giant_spider:    require('../../assets/images/monsters/giant_spider/illustration.webp'),
  gnoll:           require('../../assets/images/monsters/gnoll/illustration.webp'),
  goblin:          require('../../assets/images/monsters/goblin/illustration.webp'),
  goblin_champion: require('../../assets/images/monsters/goblin_champion/illustration.webp'),
  goblin_raider:   require('../../assets/images/monsters/goblin_raider/illustration.webp'),
  goblin_shaman:   require('../../assets/images/monsters/goblin_shaman/illustration.webp'),
  goblin_veteran:  require('../../assets/images/monsters/goblin_veteran/illustration.webp'),
  harpy:           require('../../assets/images/monsters/harpy/illustration.webp'),
  hobgoblin:       require('../../assets/images/monsters/hobgoblin/illustration.webp'),
  imp:             require('../../assets/images/monsters/imp/illustration.webp'),
  knight:          require('../../assets/images/monsters/knight/illustration.webp'),
  lich:            require('../../assets/images/monsters/lich/illustration.webp'),
  mummy:           require('../../assets/images/monsters/mummy/illustration.webp'),
  ogre:            require('../../assets/images/monsters/ogre/illustration.webp'),
  orc:             require('../../assets/images/monsters/orc/illustration.webp'),
  rat:             require('../../assets/images/monsters/rat/illustration.webp'),
  skeleton:        require('../../assets/images/monsters/skeleton/illustration.webp'),
  skeleton_archer: require('../../assets/images/monsters/skeleton_archer/illustration.webp'),
  skeleton_knight: require('../../assets/images/monsters/skeleton_knight/illustration.webp'),
  skeleton_mage:   require('../../assets/images/monsters/skeleton_mage/illustration.webp'),
  troll:           require('../../assets/images/monsters/troll/illustration.webp'),
  vampire:         require('../../assets/images/monsters/vampire/illustration.webp'),
  werewolf:        require('../../assets/images/monsters/werewolf/illustration.webp'),
  wight:           require('../../assets/images/monsters/wight/illustration.webp'),
  zombie:          require('../../assets/images/monsters/zombie/illustration.webp'),
};
