import { getDB } from './connection';

const CURRENT_VERSION = 14;

const migrations: Record<number, string[]> = {
  1: [
    // Core resource table — stores raw JSON from the 5e API per endpoint
    `CREATE TABLE IF NOT EXISTS resources (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      endpoint TEXT NOT NULL,
      index_key TEXT NOT NULL,
      name TEXT NOT NULL,
      data TEXT NOT NULL,
      UNIQUE(endpoint, index_key)
    )`,

    // Translations table — field-level i18n for every resource
    `CREATE TABLE IF NOT EXISTS translations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      endpoint TEXT NOT NULL,
      index_key TEXT NOT NULL,
      field_path TEXT NOT NULL,
      lang TEXT NOT NULL,
      value TEXT NOT NULL,
      UNIQUE(endpoint, index_key, field_path, lang)
    )`,

    // Sync metadata — tracks when each endpoint was last synced
    `CREATE TABLE IF NOT EXISTS sync_meta (
      endpoint TEXT PRIMARY KEY,
      last_synced_at TEXT NOT NULL,
      item_count INTEGER NOT NULL DEFAULT 0
    )`,

    // Indexes for fast lookups
    `CREATE INDEX IF NOT EXISTS idx_resources_endpoint ON resources(endpoint)`,
    `CREATE INDEX IF NOT EXISTS idx_resources_endpoint_index ON resources(endpoint, index_key)`,
    `CREATE INDEX IF NOT EXISTS idx_translations_lookup ON translations(endpoint, index_key, lang)`,
    `CREATE INDEX IF NOT EXISTS idx_translations_lang ON translations(lang)`,
  ],

  2: [
    // Saved games — persists seed + party roster + game progress
    `CREATE TABLE IF NOT EXISTS saved_games (
      id TEXT PRIMARY KEY,
      seed TEXT NOT NULL,
      seed_hash TEXT NOT NULL,
      party_data TEXT NOT NULL,
      floor INTEGER NOT NULL DEFAULT 1,
      cycle INTEGER NOT NULL DEFAULT 1,
      phase TEXT NOT NULL DEFAULT 'DAY',
      gold INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'active',
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,

    `CREATE INDEX IF NOT EXISTS idx_saved_games_status ON saved_games(status)`,
    `CREATE INDEX IF NOT EXISTS idx_saved_games_updated ON saved_games(updated_at DESC)`,
  ],

  3: [
    // Persist player location (village vs map) and map node states for resume
    `ALTER TABLE saved_games ADD COLUMN location TEXT NOT NULL DEFAULT 'village'`,
    `ALTER TABLE saved_games ADD COLUMN map_state TEXT`,
  ],

  4: [
    // Party portrait — base64 data URI generated by Gemini AI
    `ALTER TABLE saved_games ADD COLUMN party_portrait TEXT`,
  ],

  5: [
    // Character portraits — stored separately to keep party_data JSON lean
    // Format: JSON object mapping character index (string) to base64 data URI
    `ALTER TABLE saved_games ADD COLUMN portraits_json TEXT`,
  ],

  6: [
    // Character expression variants — map of index → { neutral, happy, angry, sad, surprised, wounded }
    // Generated via img2img from the base portrait; stored as base64 data URIs
    `ALTER TABLE saved_games ADD COLUMN expressions_json TEXT`,
  ],

  // Sprint 5B — Fractional cycle tracking + simulation events
  7: [
    `ALTER TABLE saved_games ADD COLUMN cycle_raw REAL NOT NULL DEFAULT 1.0`,
    `ALTER TABLE saved_games ADD COLUMN last_action_at TEXT`,
    `ALTER TABLE saved_games ADD COLUMN last_sim_events TEXT`,
  ],

  // Sprint 6A — Items inventory
  8: [
    `CREATE TABLE IF NOT EXISTS items (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      owner_game_id TEXT,
      owner_char_name TEXT,
      name TEXT NOT NULL,
      type TEXT NOT NULL CHECK(type IN ('weapon','armor','consumable','material','boss_loot')),
      rarity TEXT NOT NULL CHECK(rarity IN ('common','uncommon','rare','unique')),
      is_equipped INTEGER NOT NULL DEFAULT 0,
      is_unique INTEGER NOT NULL DEFAULT 0,
      obtained_cycle INTEGER NOT NULL DEFAULT 1,
      floor_obtained INTEGER NOT NULL DEFAULT 1,
      gold_value INTEGER NOT NULL DEFAULT 0,
      data TEXT NOT NULL DEFAULT '{}',
      claimed INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_items_game ON items(owner_game_id)`,
    `CREATE INDEX IF NOT EXISTS idx_items_seed ON items(seed_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_items_type ON items(type)`,
    `CREATE INDEX IF NOT EXISTS idx_items_floor ON items(floor_obtained)`,
  ],

  // Sprint 6A — World events and bounty system
  9: [
    `CREATE TABLE IF NOT EXISTS events (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      type TEXT NOT NULL,
      floor INTEGER NOT NULL,
      cycle INTEGER NOT NULL,
      party_name TEXT NOT NULL,
      target_name TEXT,
      data TEXT NOT NULL DEFAULT '{}',
      created_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_events_seed ON events(seed_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_events_cycle ON events(cycle DESC)`,
    `CREATE INDEX IF NOT EXISTS idx_events_type ON events(type)`,

    `CREATE TABLE IF NOT EXISTS bounties (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      target_game_id TEXT NOT NULL,
      issued_by TEXT NOT NULL DEFAULT 'GUILD',
      reward_amount INTEGER NOT NULL DEFAULT 0,
      bounty_level INTEGER NOT NULL DEFAULT 1,
      is_active INTEGER NOT NULL DEFAULT 1,
      kill_count INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_bounties_seed ON bounties(seed_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_bounties_active ON bounties(is_active)`,
  ],

  // Sprint 6A — Alliance system
  10: [
    `CREATE TABLE IF NOT EXISTS alliances (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      party_a TEXT NOT NULL,
      party_b TEXT NOT NULL,
      protection_fee INTEGER NOT NULL DEFAULT 0,
      expires_at_cycle INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','expired','terminated')),
      created_at TEXT NOT NULL,
      created_cycle INTEGER NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_alliances_seed ON alliances(seed_hash)`,
    `CREATE INDEX IF NOT EXISTS idx_alliances_party_a ON alliances(party_a)`,
    `CREATE INDEX IF NOT EXISTS idx_alliances_status ON alliances(status)`,
  ],

  // Sprint 6F — Safe zone tracking (doc 11)
  11: [
    `ALTER TABLE saved_games ADD COLUMN in_safe_zone INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE saved_games ADD COLUMN safe_zone_room_id TEXT`,
  ],

  // Sprint 6C — Party lifecycle and origin (doc 12)
  12: [
    `ALTER TABLE saved_games ADD COLUMN party_origin TEXT NOT NULL DEFAULT 'PLAYER'`,
    `ALTER TABLE saved_games ADD COLUMN predecessor_game_id TEXT`,
    `ALTER TABLE saved_games ADD COLUMN created_by_player INTEGER NOT NULL DEFAULT 1`,
    `ALTER TABLE saved_games ADD COLUMN elimination_reason TEXT`,
  ],

  // Sprint 7 — Essence system + monster kills tracking (doc 13)
  13: [
    `CREATE TABLE IF NOT EXISTS essences (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      owner_game_id TEXT NOT NULL,
      owner_char_name TEXT NOT NULL,
      definition_id TEXT NOT NULL,
      rank INTEGER NOT NULL,
      evolution_level INTEGER NOT NULL DEFAULT 1,
      kills_on_type INTEGER NOT NULL DEFAULT 0,
      equipped INTEGER NOT NULL DEFAULT 0,
      obtained_cycle INTEGER NOT NULL,
      obtained_floor INTEGER NOT NULL,
      created_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_essences_game ON essences(owner_game_id)`,
    `CREATE INDEX IF NOT EXISTS idx_essences_char ON essences(owner_char_name)`,

    `CREATE TABLE IF NOT EXISTS monster_kills (
      id TEXT PRIMARY KEY,
      seed_hash TEXT NOT NULL,
      game_id TEXT NOT NULL,
      char_name TEXT NOT NULL,
      monster_key TEXT NOT NULL,
      kill_count INTEGER NOT NULL DEFAULT 0,
      last_kill_cycle INTEGER NOT NULL,
      updated_at TEXT NOT NULL,
      UNIQUE(game_id, char_name, monster_key)
    )`,
    `CREATE INDEX IF NOT EXISTS idx_monster_kills_game ON monster_kills(game_id)`,
  ],

  // Sprint 5C — Rival persistence (GAP-01)
  14: [
    `CREATE TABLE IF NOT EXISTS rival_states (
      id          TEXT PRIMARY KEY,
      seed_hash   TEXT NOT NULL,
      floor       INTEGER NOT NULL,
      rep         INTEGER DEFAULT 0,
      profile     TEXT NOT NULL,
      memory      TEXT NOT NULL,
      last_cycle  INTEGER NOT NULL,
      updated_at  TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_rival_states_seed ON rival_states (seed_hash)`,
  ],
};

export function runMigrations(): void {
  const db = getDB();

  db.executeSync(
    `CREATE TABLE IF NOT EXISTS schema_version (
      version INTEGER PRIMARY KEY
    )`,
  );

  const result = db.executeSync('SELECT MAX(version) as v FROM schema_version');
  const currentVersion = (result.rows?.[0]?.v as number) ?? 0;

  for (let v = currentVersion + 1; v <= CURRENT_VERSION; v++) {
    const statements = migrations[v];
    if (statements) {
      db.executeSync('BEGIN TRANSACTION');
      try {
        for (const sql of statements) {
          db.executeSync(sql);
        }
        db.executeSync('INSERT INTO schema_version (version) VALUES (?)', [v]);
        db.executeSync('COMMIT');
      } catch (error) {
        db.executeSync('ROLLBACK');
        throw error;
      }
    }
  }
}
