/**
 * WorldEvent — domain entity for simulation events that shape the world log.
 * These are generated by the world simulator and presented in WorldLogScreen.
 * Immutable.
 */

export type WorldEventType =
  | 'AI_COMBAT_WIN'
  | 'AI_COMBAT_LOSS'
  | 'AI_FLOOR_ADVANCE'
  | 'AI_REST'
  | 'AI_ELIMINATED'
  | 'AI_PARTY_SPAWNED'
  | 'BOSS_KILLED'
  | 'ALLIANCE_FORMED'
  | 'BOUNTY_ISSUED';

export interface WorldEventProps {
  type: WorldEventType;
  cycle: number;
  floor: number;
  partyName: string;
  targetName?: string;
  summary: string;
  summary_en: string;
  rivalAge?: number;
}

export class WorldEvent {
  constructor(private readonly props: WorldEventProps) {}

  get type(): WorldEventType { return this.props.type; }
  get cycle(): number { return this.props.cycle; }
  get floor(): number { return this.props.floor; }
  get partyName(): string { return this.props.partyName; }
  get targetName(): string | undefined { return this.props.targetName; }
  get summary(): string { return this.props.summary; }
  get summary_en(): string { return this.props.summary_en; }
  get rivalAge(): number | undefined { return this.props.rivalAge; }

  toProps(): WorldEventProps { return { ...this.props }; }
  static fromProps(props: WorldEventProps): WorldEvent { return new WorldEvent(props); }
}
